/* 
  Sketch generated by the Arduino IoT Cloud Thing "Untitled"
  https://create.arduino.cc/cloud/things/6d7c853e-50d7-48ae-829f-13e12af80828 

  Arduino IoT Cloud Variables description

  The following variables are automatically generated and updated when changes are made to the Thing

  bool lEDswitch;
  bool lEDswitch2;
  bool ledswitch3;
  bool ledswitch4;
  bool lEDswitch5;

  Variables which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/

#include "thingProperties.h"
const int red1 = 23;
const int red2 = 22;
const int red3 = 21;
const int red4 = 19;

const int yellow1 = 18;
const int yellow2 = 5;
const int yellow3 = 17;
const int yellow4 = 16;

const int green1 = 26;
const int green2 = 25;
const int green3 = 32;
const int green4 = 33;

const int yellow5 = 15;

void setup() {
    pinMode(red1, OUTPUT); pinMode(yellow1, OUTPUT); pinMode(green1, OUTPUT);
    pinMode(red2, OUTPUT); pinMode(yellow2, OUTPUT); pinMode(green2, OUTPUT);
    pinMode(red3, OUTPUT); pinMode(yellow3, OUTPUT); pinMode(green3, OUTPUT);
    pinMode(red4, OUTPUT); pinMode(yellow4, OUTPUT); pinMode(green4, OUTPUT);
  
    pinMode(yellow5, OUTPUT);
    
  // Initialize serial and wait for port to open:
  Serial.begin(9600);
  // This delay gives the chance to wait for a Serial Monitor without blocking if none is found
  delay(1500); 

  // Defined in thingProperties.h
  initProperties();

  // Connect to Arduino IoT Cloud
  ArduinoCloud.begin(ArduinoIoTPreferredConnection);
  
  /*
     The following function allows you to obtain more information
     related to the state of network and IoT Cloud connection and errors
     the higher number the more granular information you’ll get.
     The default is 0 (only errors).
     Maximum is 4
 */
  setDebugMessageLevel(2);
  ArduinoCloud.printDebugInfo();
}

void loop() {
  ArduinoCloud.update();
  // Your code here 
  if(lEDswitch == true) {
      // 1st GREEN Signal
digitalWrite(red1,LOW);digitalWrite(yellow1,LOW);digitalWrite(green1,HIGH);
digitalWrite(red2,HIGH);digitalWrite(yellow2,LOW);digitalWrite(green2,LOW);
digitalWrite(red3,HIGH);digitalWrite(yellow3,LOW);digitalWrite(green3,LOW);
digitalWrite(red4,HIGH);digitalWrite(yellow4,LOW);digitalWrite(green4,LOW);
delay(5000);

  // Yellow Light
digitalWrite(red1,LOW);digitalWrite(yellow1,HIGH);digitalWrite(green1,LOW);
digitalWrite(red2,LOW);digitalWrite(yellow2,HIGH);digitalWrite(green2,LOW);
digitalWrite(red3,HIGH);digitalWrite(yellow3,LOW);digitalWrite(green3,LOW);
digitalWrite(red4,HIGH);digitalWrite(yellow4,LOW);digitalWrite(green4,LOW);
delay(1000);

  // 2nd GREEN Signal
digitalWrite(red1,HIGH);digitalWrite(yellow1,LOW);digitalWrite(green1,LOW);
digitalWrite(red2,LOW);digitalWrite(yellow2,LOW);digitalWrite(green2,HIGH);
digitalWrite(red3,HIGH);digitalWrite(yellow3,LOW);digitalWrite(green3,LOW);
digitalWrite(red4,HIGH);digitalWrite(yellow4,LOW);digitalWrite(green4,LOW);
delay(5000);

  // Yellow Light
digitalWrite(red1,HIGH);digitalWrite(yellow1,LOW);digitalWrite(green1,LOW);
digitalWrite(red2,LOW);digitalWrite(yellow2,HIGH);digitalWrite(green2,LOW);
digitalWrite(red3,LOW);digitalWrite(yellow3,HIGH);digitalWrite(green3,LOW);
digitalWrite(red4,HIGH);digitalWrite(yellow4,LOW);digitalWrite(green4,LOW);
delay(1000);

  // 3rd GREEN Signal
digitalWrite(red1,HIGH);digitalWrite(yellow1,LOW);digitalWrite(green1,LOW);
digitalWrite(red2,HIGH);digitalWrite(yellow2,LOW);digitalWrite(green2,LOW);
digitalWrite(red3,LOW);digitalWrite(yellow3,LOW);digitalWrite(green3,HIGH);
digitalWrite(red4,HIGH);digitalWrite(yellow4,LOW);digitalWrite(green4,LOW);
delay(5000);

  // Yellow Light
digitalWrite(red1,HIGH);digitalWrite(yellow1,LOW);digitalWrite(green1,LOW);
digitalWrite(red2,HIGH);digitalWrite(yellow2,LOW);digitalWrite(green2,LOW);
digitalWrite(red3,LOW);digitalWrite(yellow3,HIGH);digitalWrite(green3,LOW);
digitalWrite(red4,LOW);digitalWrite(yellow4,HIGH);digitalWrite(green4,LOW);
delay(1000);

  // 4th GREEN Signal
digitalWrite(red1,HIGH);digitalWrite(yellow1,LOW);digitalWrite(green1,LOW);
digitalWrite(red2,HIGH);digitalWrite(yellow2,LOW);digitalWrite(green2,LOW);
digitalWrite(red3,HIGH);digitalWrite(yellow3,LOW);digitalWrite(green3,LOW);
digitalWrite(red4,LOW);digitalWrite(yellow4,LOW);digitalWrite(green4,HIGH);
delay(5000);

  // Yellow Light
digitalWrite(red1,LOW);digitalWrite(yellow1,HIGH);digitalWrite(green1,LOW);
digitalWrite(red2,HIGH);digitalWrite(yellow2,LOW);digitalWrite(green2,LOW);
digitalWrite(red3,HIGH);digitalWrite(yellow3,LOW);digitalWrite(green3,LOW);
digitalWrite(red4,LOW);digitalWrite(yellow4,HIGH);digitalWrite(green4,LOW);
delay(1000);
  } else if (lEDswitch2 == true) {
      // 1st GREEN Signal
digitalWrite(red1,LOW);
digitalWrite(red2,LOW);
digitalWrite(red3,LOW);
digitalWrite(red4,LOW);

  // Yellow Light
digitalWrite(green1,LOW);
digitalWrite(green2,LOW);
digitalWrite(green3,LOW);
digitalWrite(green4,LOW);


  // 4th GREEN Signal
digitalWrite(yellow1,HIGH);
digitalWrite(yellow2,HIGH);
digitalWrite(yellow3,HIGH);
digitalWrite(yellow4,HIGH);
delay(3000);

  // Yellow Light
digitalWrite(yellow1,LOW);
digitalWrite(yellow2,LOW);
digitalWrite(yellow3,LOW);
digitalWrite(yellow4,LOW);
delay(1000);
  } 
else if(ledswitch3 == true) {
digitalWrite(red1,HIGH);digitalWrite(yellow1,LOW);digitalWrite(green1,LOW);
digitalWrite(red2,HIGH);digitalWrite(yellow2,LOW);digitalWrite(green2,LOW);


digitalWrite(red3,LOW);digitalWrite(yellow3,LOW);digitalWrite(green3,HIGH);
digitalWrite(red4,LOW);digitalWrite(yellow4,LOW);digitalWrite(green4,HIGH);
  } 
else if(ledswitch4 == true) {
digitalWrite(red1,LOW);digitalWrite(yellow1,LOW);digitalWrite(green1,HIGH);
digitalWrite(red2,LOW);digitalWrite(yellow2,LOW);digitalWrite(green2,HIGH);


digitalWrite(red3,HIGH);digitalWrite(yellow3,LOW);digitalWrite(green3,LOW);
digitalWrite(red4,HIGH);digitalWrite(yellow4,LOW);digitalWrite(green4,LOW);
                            } 
else if(lEDswitch5 == true) {
digitalWrite(yellow5,HIGH);
  // yellow led for cross the road
digitalWrite(red1,HIGH);
digitalWrite(red2,HIGH);
digitalWrite(red3,HIGH);
digitalWrite(red4,HIGH);
                            } 
else {
    digitalWrite(red1, LOW);
    digitalWrite(red2, LOW);
    digitalWrite(red3, LOW);
    digitalWrite(red4, LOW);
    
    digitalWrite(yellow1, LOW);
    digitalWrite(yellow2, LOW);
    digitalWrite(yellow3, LOW);
    digitalWrite(yellow4, LOW);
    
    digitalWrite(green1, LOW);
    digitalWrite(green2, LOW);
    digitalWrite(green3, LOW);
    digitalWrite(green4, LOW);
    
    digitalWrite(yellow5, LOW); 
    }
  
}


/*
  Since LEDswitch is READ_WRITE variable, onLEDswitchChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onLEDswitchChange()  {
  // Add your code here to act upon LEDswitch change
}

/*
  Since LEDswitch2 is READ_WRITE variable, onLEDswitch2Change() is
  executed every time a new value is received from IoT Cloud.
*/
void onLEDswitch2Change()  {
  // Add your code here to act upon LEDswitch2 change
}

/*
  Since Ledswitch3 is READ_WRITE variable, onLedswitch3Change() is
  executed every time a new value is received from IoT Cloud.
*/
void onLedswitch3Change()  {
  // Add your code here to act upon Ledswitch3 change
}


/*
  Since Ledswitch4 is READ_WRITE variable, onLedswitch4Change() is
  executed every time a new value is received from IoT Cloud.
*/
void onLedswitch4Change()  {
  // Add your code here to act upon Ledswitch4 change
}

/*
  Since LEDswitch5 is READ_WRITE variable, onLEDswitch5Change() is
  executed every time a new value is received from IoT Cloud.
*/
void onLEDswitch5Change()  {
  // Add your code here to act upon LEDswitch5 change
}